notifications: # set notification options
  email:
    recipients:

    # change is when the repo status goes from pass to fail or vice versa
    on_success: never
    on_failure: change
  # Or we could just disable all email

install:
  - yarn install

script:
  - yarn run test